DESCRIPTION = "Protocol Buffers are Google's language-neutral, platform-neutral, extensible mechanism for serializing structured data."
HOMEPAGE = "https://developers.google.com/protocol-buffers/"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=35953c752efc9299b184f91bef540095"

PV = "3.5.0"

SRC_URI = "git://github.com/google/protobuf.git"
SRCREV = "0cd2ad11b8a114c3767aafe9912c09c89bfd0f3e"

S = "${WORKDIR}/git"
