#!/bin/sh

# Merge meta-fsp2-drivers/adals/apps layers inside the meta-openbmc-bsp/meta-ibm layer
THIS_SCRIPT=$BASH_SOURCE

echo " Change directory to meta-openbmc-bsp/meta-ibm/ for cloning fsp2 drivers/adals/apps layer" 
cd meta-openbmc-bsp/meta-ibm/

dir=meta-fsp2-ibm-internal

if [[ ! -e $dir ]]; then
	echo "$dir Does not exist Need to clone it"
    git clone git@github.ibm.com:XXPETRI/meta-fsp2-ibm-internal.git
else
    echo "$dir already exists so not cloning it"
fi

echo " Change directory to OE root directory " 

cd ../../

